FROM golang:1-stretch

ARG GOOS=linux
ARG GOARCH=amd64

ARG GITHUB_TOKEN
ARG GITHUB_SHA
ARG GITHUB_REF
ARG GITHUB_REPOSITORY
ARG REPOSITORY=scrivener

ENV GITHUB_TOKEN=$GITHUB_TOKEN
ENV GITHUB_SHA=$GITHUB_SHA
ENV GITHUB_REF=$GITHUB_REF
ENV GITHUB_REPOSITORY=$GITHUB_REPOSITORY
ENV REPOSITORY=$REPOSITORY

RUN apt-get update && apt-get install -y --no-install-recommends \
		make \
		zip \
		jq \
		curl

WORKDIR ./src/azillion/scrivener
COPY . ./

RUN chmod 777 ./Makefile

RUN make
